/*
|--------------------------------------------|
         ⚡️ Generated by Agentsmith ⚡️
      ⚠️ Do not edit this file directly ⚠️
|--------------------------------------------|
*/

export type PromptVariables__support_chat__0_1_0 = {
  userMessage: string;
};

export type PromptConfig__support_chat__0_1_0 = any;

export type PromptVersion__support_chat__0_1_0 = {
  version: '0.1.0';
  config: PromptConfig__support_chat__0_1_0;
  variables: PromptVariables__support_chat__0_1_0;
  content: string;
};

export type PromptVariables__support_chat__0_0_1 = {
  userMessage: string;
};

export type PromptConfig__support_chat__0_0_1 = any;

export type PromptVersion__support_chat__0_0_1 = {
  version: '0.0.1';
  config: PromptConfig__support_chat__0_0_1;
  variables: PromptVariables__support_chat__0_0_1;
  content: string;
};

export type Prompt__support_chat = {
  name: 'Support Chat';
  slug: 'support-chat';
  versions: {
    latest: PromptVersion__support_chat__0_1_0;
    '0.1.0': PromptVersion__support_chat__0_1_0;
    '0.0.1': PromptVersion__support_chat__0_0_1;
  };
};

export type PromptVariables__hello_world__0_0_3 = {
  firstName: string;
  lastName: string;
};

export type PromptConfig__hello_world__0_0_3 = any;

export type PromptVersion__hello_world__0_0_3 = {
  version: '0.0.3';
  config: PromptConfig__hello_world__0_0_3;
  variables: PromptVariables__hello_world__0_0_3;
  content: string;
};

export type PromptVariables__hello_world__0_0_2 = {
  name: string;
};

export type PromptConfig__hello_world__0_0_2 = any;

export type PromptVersion__hello_world__0_0_2 = {
  version: '0.0.2';
  config: PromptConfig__hello_world__0_0_2;
  variables: PromptVariables__hello_world__0_0_2;
  content: string;
};

export type PromptVariables__hello_world__0_0_1 = {};

export type PromptConfig__hello_world__0_0_1 = any;

export type PromptVersion__hello_world__0_0_1 = {
  version: '0.0.1';
  config: PromptConfig__hello_world__0_0_1;
  variables: PromptVariables__hello_world__0_0_1;
  content: string;
};

export type Prompt__hello_world = {
  name: 'Hello World';
  slug: 'hello-world';
  versions: {
    latest: PromptVersion__hello_world__0_0_3;
    '0.0.3': PromptVersion__hello_world__0_0_3;
    '0.0.2': PromptVersion__hello_world__0_0_2;
    '0.0.1': PromptVersion__hello_world__0_0_1;
  };
};

export type PromptVariables__unpublished_prompt__0_0_1 = {};

export type PromptConfig__unpublished_prompt__0_0_1 = any;

export type PromptVersion__unpublished_prompt__0_0_1 = {
  version: '0.0.1';
  config: PromptConfig__unpublished_prompt__0_0_1;
  variables: PromptVariables__unpublished_prompt__0_0_1;
  content: string;
};

export type Prompt__unpublished_prompt = {
  name: 'Unpublished Prompt';
  slug: 'unpublished-prompt';
  versions: {
    latest: never;
    '0.0.1': PromptVersion__unpublished_prompt__0_0_1;
  };
};

export type PromptVariables__streaming_prompt__0_0_1 = {};

export type PromptConfig__streaming_prompt__0_0_1 = {
  stream: true;
};

export type PromptVersion__streaming_prompt__0_0_1 = {
  version: '0.0.1';
  config: PromptConfig__streaming_prompt__0_0_1;
  variables: PromptVariables__streaming_prompt__0_0_1;
  content: string;
};

export type Prompt__streaming_prompt = {
  name: 'Streaming Prompt';
  slug: 'streaming-prompt';
  versions: {
    latest: never;
    '0.0.1': PromptVersion__streaming_prompt__0_0_1;
  };
};

export type PromptVariables__non_streaming_prompt__0_0_1 = {};

export type PromptConfig__non_streaming_prompt__0_0_1 = {};

export type PromptVersion__non_streaming_prompt__0_0_1 = {
  version: '0.0.1';
  config: PromptConfig__non_streaming_prompt__0_0_1;
  variables: PromptVariables__non_streaming_prompt__0_0_1;
  content: string;
};

export type Prompt__non_streaming_prompt = {
  name: 'Non-Streaming Prompt';
  slug: 'non-streaming-prompt';
  versions: {
    latest: never;
    '0.0.1': PromptVersion__non_streaming_prompt__0_0_1;
  };
};

export type PromptVariables__tool_prompt__0_0_1 = {};

export type PromptConfig__tool_prompt__0_0_1 = {
  model: string;
};

export type PromptVersion__tool_prompt__0_0_1 = {
  version: '0.0.1';
  config: PromptConfig__tool_prompt__0_0_1;
  variables: PromptVariables__tool_prompt__0_0_1;
  content: string;
};

export type Prompt__tool_prompt = {
  name: 'Tool Prompt';
  slug: 'tool-prompt';
  versions: {
    latest: PromptVersion__tool_prompt__0_0_1;
    '0.0.1': PromptVersion__tool_prompt__0_0_1;
  };
};

export type PromptVariables__include_prompt__0_0_1 = {
  foo: string;
};

export type PromptConfig__include_prompt__0_0_1 = {
  models: ['openrouter/auto'];
  temperature: number;
};

export type PromptVersion__include_prompt__0_0_1 = {
  version: '0.0.1';
  config: PromptConfig__include_prompt__0_0_1;
  variables: PromptVariables__include_prompt__0_0_1 & PromptVariables__included_prompt__0_0_2;
  content: string;
};

export type PromptVariables__include_prompt__0_0_2 = {
  foo: string;
};

export type PromptConfig__include_prompt__0_0_2 = {
  models: ['openrouter/auto'];
  temperature: number;
};

export type PromptVersion__include_prompt__0_0_2 = {
  version: '0.0.2';
  config: PromptConfig__include_prompt__0_0_2;
  variables: PromptVariables__include_prompt__0_0_2 & PromptVariables__included_prompt__0_0_1;
  content: string;
};

export type PromptVariables__include_prompt__0_0_3 = {
  foo: string;
};

export type PromptConfig__include_prompt__0_0_3 = {
  models: ['openrouter/auto'];
  temperature: number;
};

export type PromptVersion__include_prompt__0_0_3 = {
  version: '0.0.3';
  config: PromptConfig__include_prompt__0_0_3;
  variables: PromptVariables__include_prompt__0_0_3 &
    PromptVariables__included_prompt__0_0_1 &
    PromptVariables__support_chat__0_1_0;
  content: string;
};

export type PromptVariables__include_prompt__0_0_4 = {
  foo: string;
};

export type PromptConfig__include_prompt__0_0_4 = {
  models: ['openrouter/auto'];
  temperature: number;
};

export type PromptVersion__include_prompt__0_0_4 = {
  version: '0.0.4';
  config: PromptConfig__include_prompt__0_0_4;
  variables: PromptVariables__include_prompt__0_0_4 &
    PromptVariables__included_prompt__0_0_1 &
    PromptVariables__included_prompt__0_0_2;
  content: string;
};

export type Prompt__include_prompt = {
  name: 'Include Prompt';
  slug: 'include-prompt';
  versions: {
    latest: PromptVersion__include_prompt__0_0_2;
    '0.0.1': PromptVersion__include_prompt__0_0_1;
    '0.0.2': PromptVersion__include_prompt__0_0_2;
    '0.0.3': PromptVersion__include_prompt__0_0_3;
    '0.0.4': PromptVersion__include_prompt__0_0_4;
  };
};

export type PromptVariables__included_prompt__0_0_1 = {
  bar: string;
};

export type PromptConfig__included_prompt__0_0_1 = {
  models: ['openrouter/auto'];
  temperature: number;
};

export type PromptVersion__included_prompt__0_0_1 = {
  version: '0.0.1';
  config: PromptConfig__included_prompt__0_0_1;
  variables: PromptVariables__included_prompt__0_0_1;
  content: string;
};

export type PromptVariables__included_prompt__0_0_2 = {
  bar: string;
};

export type PromptConfig__included_prompt__0_0_2 = {
  models: ['openrouter/auto'];
  temperature: number;
};

export type PromptVersion__included_prompt__0_0_2 = {
  version: '0.0.2';
  config: PromptConfig__included_prompt__0_0_2;
  variables: PromptVariables__included_prompt__0_0_2;
  content: string;
};

export type PromptVariables__included_prompt__0_0_3 = {
  bar: string;
  foo: string;
};

export type PromptConfig__included_prompt__0_0_3 = {
  models: ['openrouter/auto'];
  temperature: number;
};

export type PromptVersion__included_prompt__0_0_3 = {
  version: '0.0.3';
  config: PromptConfig__included_prompt__0_0_3;
  variables: PromptVariables__included_prompt__0_0_3;
  content: string;
};

export type Prompt__included_prompt = {
  name: 'Included Prompt';
  slug: 'included-prompt';
  versions: {
    latest: PromptVersion__included_prompt__0_0_2;
    '0.0.1': PromptVersion__included_prompt__0_0_1;
    '0.0.2': PromptVersion__included_prompt__0_0_2;
    '0.0.3': PromptVersion__included_prompt__0_0_3;
  };
};

export type Globals = {
  gitHubUrl: 'https://github.com/chad-syntax/agentsmith';
  supportUrl: 'https://agentsmith.app/support';
  companyName: 'Agentsmith';
  supportEmail: 'support@agentsmith.dev';
};

export type Agency = {
  prompts: {
    'support-chat': Prompt__support_chat;
    'hello-world': Prompt__hello_world;
    'unpublished-prompt': Prompt__unpublished_prompt;
    'streaming-prompt': Prompt__streaming_prompt;
    'non-streaming-prompt': Prompt__non_streaming_prompt;
    'tool-prompt': Prompt__tool_prompt;
    'include-prompt': Prompt__include_prompt;
    'included-prompt': Prompt__included_prompt;
  };
  globals: Globals;
};
