-- Agentsmith Users
create table agentsmith_users (
    id bigint generated by default as identity not null primary key,
    auth_user_id uuid references auth.users(id) not null,
    email text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index on agentsmith_users(auth_user_id);
create index on agentsmith_users(created_at);
create index on agentsmith_users(updated_at);

alter table agentsmith_users enable row level security;

create or replace function agentsmith_user_id()
returns bigint
language sql
security definer
set search_path = ''
as $$
  select id from public.agentsmith_users
  where auth_user_id = (select auth.uid());
$$;

create policy "Users can view their own record"
    on agentsmith_users for select
    to authenticated
    using (auth_user_id = (select auth.uid()));


create trigger trigger_updated_at_agentsmith_users
    before update on agentsmith_users
    for each row
    execute function set_updated_at();
