-- Global Contexts Table
create table global_contexts (
    id bigint generated by default as identity not null primary key,
    project_id bigint references projects(id),
    content jsonb not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- Indexes
create index on global_contexts(project_id);
create index on global_contexts(created_at);
create index on global_contexts(updated_at);

-- RLS
alter table global_contexts enable row level security;

-- Policies
create policy "Users can view global contexts they have access to"
    on global_contexts for select
    to authenticated
    using (has_project_access(project_id));

create policy "Users can update global contexts they have access to"
    on global_contexts for update
    to authenticated
    using (has_project_access(project_id));

create policy "Admins can delete global contexts they have access to"
    on global_contexts for delete
    to authenticated
    using (
        has_project_access(project_id) and 
        is_organization_admin((select organization_id from projects where id = project_id))
    );

-- Triggers
create trigger trigger_updated_at_global_contexts
    before update on global_contexts
    for each row
    execute function set_updated_at(); 