-- Prompts Table
create table prompts (
    id bigint generated by default as identity not null primary key,
    uuid uuid not null unique default uuid_generate_v4(),
    project_id bigint references projects(id) not null,
    name text not null,
    slug text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(project_id, slug)
);

-- Indexes
create index on prompts(project_id);
create index on prompts(created_at);
create index on prompts(updated_at);

-- RLS
alter table prompts enable row level security;

-- Helper Function for RLS
create or replace function has_prompt_access(prompt_id bigint)
returns boolean
language sql
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.prompts pr
    join public.projects p on p.id = pr.project_id
    join public.organization_users ou on ou.organization_id = p.organization_id
    where pr.id = prompt_id
    and ou.user_id = public.agentsmith_user_id()
  );
$$;

-- Policies
create policy "Users can view prompts they have access to"
    on prompts for select
    to authenticated
    using (has_project_access(project_id));

create policy "Users can create prompts in projects they have access to"
    on prompts for insert
    to authenticated
    with check (has_project_access(project_id));

create policy "Users can update prompts they have access to"
    on prompts for update
    to authenticated
    using (has_project_access(project_id));

create policy "Users can delete prompts they have access to"
    on prompts for delete
    to authenticated
    using (has_project_access(project_id));

-- Triggers
create trigger trigger_updated_at_prompts
    before update on prompts
    for each row
    execute function set_updated_at(); 