-- Prompt Versions Table
create table prompt_versions (
    id bigint generated by default as identity not null primary key,
    uuid uuid not null unique default uuid_generate_v4(),
    prompt_id bigint references prompts(id) not null,
    config jsonb not null,
    content text not null,
    version text not null check (version ~ E'^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$'),
    status prompt_status not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- Indexes
create index on prompt_versions(version);
create index on prompt_versions(prompt_id);
create index on prompt_versions(created_at);
create index on prompt_versions(updated_at);

-- RLS
alter table prompt_versions enable row level security;

-- Policies
create policy "Users can view prompt versions they have access to"
    on prompt_versions for select
    to authenticated
    using (has_prompt_access(prompt_id));

create policy "Users can create prompt versions they have access to"
    on prompt_versions for insert
    to authenticated
    with check (has_prompt_access(prompt_id));

create policy "Users can update prompt versions they have access to"
    on prompt_versions for update
    to authenticated
    using (has_prompt_access(prompt_id));

create policy "Users can delete prompt versions they have access to"
    on prompt_versions for delete
    to authenticated
    using (has_prompt_access(prompt_id));

-- Triggers
create trigger trigger_updated_at_prompt_versions
    before update on prompt_versions
    for each row
    execute function set_updated_at(); 