-- Prompt Variables Table
create table prompt_variables (
    id bigint generated by default as identity not null primary key,
    prompt_version_id bigint references prompt_versions(id),
    name text not null,
    type variable_type not null,
    required boolean not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- Indexes
create index on prompt_variables(prompt_version_id);

-- RLS
alter table prompt_variables enable row level security;

-- Policies
create policy "Users can view prompt variables they have access to"
    on prompt_variables for select
    to authenticated
    using (exists (
        select 1 from prompt_versions pv
        where pv.id = prompt_version_id
        and has_prompt_access(pv.prompt_id)
    ));

create policy "Users can create prompt variables they have access to"
    on prompt_variables for insert
    to authenticated
    with check (exists (
        select 1 from prompt_versions pv
        where pv.id = prompt_version_id
        and has_prompt_access(pv.prompt_id)
    ));

create policy "Users can update prompt variables they have access to"
    on prompt_variables for update
    to authenticated
    using (exists (
        select 1 from prompt_versions pv
        where pv.id = prompt_version_id
        and has_prompt_access(pv.prompt_id)
    ));

create policy "Users can delete prompt variables they have access to"
    on prompt_variables for delete
    to authenticated
    using (exists (
        select 1 from prompt_versions pv
        where pv.id = prompt_version_id
        and has_prompt_access(pv.prompt_id)
    ));

-- Triggers
create trigger trigger_updated_at_prompt_variables
    before update on prompt_variables
    for each row
    execute function set_updated_at(); 