-- LLM Logs (TimescaleDB Table)
create table llm_logs (
    id bigint generated by default as identity not null,
    uuid uuid not null default uuid_generate_v4(),
    project_id bigint references projects(id) not null,
    prompt_version_id bigint references prompt_versions(id) not null,
    prompt_variables jsonb not null,
    raw_input jsonb not null,
    raw_output jsonb,
    start_time timestamptz not null,
    end_time timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(id, created_at),
    unique(uuid, created_at)
);

-- Indexes
create index on llm_logs(project_id, created_at);
create index on llm_logs(prompt_version_id, created_at);
create index on llm_logs(start_time, created_at);
create index on llm_logs(end_time, created_at);

-- Triggers
create trigger trigger_updated_at_llm_logs
    before update on llm_logs
    for each row
    execute function set_updated_at();

-- Enable Row Level Security
alter table llm_logs enable row level security;

-- Policies
create policy llm_logs_project_access_policy
    on llm_logs
    for select
    to authenticated
    using (has_project_access(project_id));

create policy llm_logs_project_insert_policy
    on llm_logs
    for insert
    to authenticated
    with check (has_project_access(project_id));

create policy llm_logs_project_update_policy
    on llm_logs
    for update
    to authenticated
    using (has_project_access(project_id))
    with check (has_project_access(project_id));

create policy llm_logs_project_delete_policy
    on llm_logs
    for delete
    to authenticated
    using (false);

-- Create Hypertable
select create_hypertable('llm_logs', 'created_at'); 