-- GitHub App Installations Table
create table github_app_installations (
    id bigint generated by default as identity not null primary key,
    organization_id bigint references organizations(id) not null,
    github_account_id bigint not null,
    installation_id bigint not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(organization_id, installation_id)
);

-- Indexes
create index on github_app_installations(organization_id);
create index on github_app_installations(github_account_id);
create index on github_app_installations(installation_id);
create index on github_app_installations(created_at);

-- RLS
alter table github_app_installations enable row level security;

-- Policies
create policy "Users can view github app installations they have access to"
    on github_app_installations for select
    to authenticated
    using (is_organization_member(organization_id));

create policy "Organization admins can update github app installations for their organization"
    on github_app_installations for update
    to authenticated
    using (is_organization_admin(organization_id));

create policy "Organization admins can delete github app installations for their organization"
    on github_app_installations for delete
    to authenticated
    using (is_organization_admin(organization_id));

create policy "Organization admins can create github app installations for their organization"
    on github_app_installations for insert
    to authenticated
    with check (is_organization_admin(organization_id));

-- Triggers
create trigger trigger_updated_at_github_app_installations
    before update on github_app_installations
    for each row
    execute function set_updated_at(); 