-- Project Repositories Table
create table project_repositories (
    id bigint generated by default as identity not null primary key,
    project_id bigint references projects(id) not null,
    organization_id bigint references organizations(id) not null,
    github_app_installation_id bigint references github_app_installations(id) not null,
    agentsmith_folder text not null,
    repository_id bigint not null,
    repository_name text not null,
    repository_full_name text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(project_id, repository_id)
);

-- Indexes
create index on project_repositories(project_id);
create index on project_repositories(organization_id);
create index on project_repositories(github_app_installation_id);
create index on project_repositories(repository_id);
create index on project_repositories(created_at);

-- RLS
alter table project_repositories enable row level security;

-- Policies
create policy "Users can view project repositories they have access to"
    on project_repositories for select
    to authenticated
    using (has_project_access(project_id));

create policy "Organization admins can update project repositories they have access to"
    on project_repositories for update
    to authenticated
    using (is_organization_admin(organization_id));

create policy "Organization admins can delete project repositories they have access to"
    on project_repositories for delete
    to authenticated
    using (is_organization_admin(organization_id));

create policy "Organization admins can create project repositories for their organization"
    on project_repositories for insert
    to authenticated
    with check (is_organization_admin(organization_id));

-- Triggers
create trigger trigger_updated_at_project_repositories
    before update on project_repositories
    for each row
    execute function set_updated_at(); 