// ⚡️ Generated by AgentSmith ⚡️
// ⚠️ Do not edit this file directly ⚠️
export type PromptSlug =
  | 'qualify_lead'
  | 'detect_super_qualified_lead'
  | 'lead_urgency_assessment'
  | 'budget_alignment_verification'
  | 'technical_fit_assessment'
  | 'default_system_prompt';
export type Prompt = {
  id: string;
  name: string;
  content: string;
  version: string;
  variables: PromptVariable[];
  slug: PromptSlug;
};
export type PromptVariable = {
  name: string;
  type: 'string' | 'number' | 'boolean';
  required: boolean;
};
export type AgentAction = {
  id: string;
  name: string;
  slug: string;
  prompt_id: string;
};
export type AGENT_TRIGGERS = {
  AFTER_ANY_MESSAGE: 'AFTER_ANY_MESSAGE';
  BEFORE_ANY_MESSAGE: 'BEFORE_ANY_MESSAGE';
  AFTER_USER_MESSAGE: 'AFTER_USER_MESSAGE';
  AFTER_ASSISTANT_MESSAGE: 'AFTER_ASSISTANT_MESSAGE';
  BEFORE_USER_MESSAGE: 'BEFORE_USER_MESSAGE';
  BEFORE_ASSISTANT_MESSAGE: 'BEFORE_ASSISTANT_MESSAGE';
  BEFORE_INSTANCE_CLEANUP: 'BEFORE_INSTANCE_CLEANUP';
  CRON_SCHEDULE: 'CRON_SCHEDULE';
};
export type AgentTriggers = keyof AGENT_TRIGGERS;
export type AgentTrigger = {
  type: AgentTriggers;
  cron_schedule?: string;
} & (
  | {
      type: 'CRON_SCHEDULE';
      cron_schedule: string;
    }
  | {
      type: Exclude<AgentTriggers, 'CRON_SCHEDULE'>;
      cron_schedule?: never;
    }
);
export type AgentReaction = {
  id: string;
  name: string;
  slug: string;
  prompt_id: string;
  triggers: AgentTrigger[];
};
export type Agent = {
  id: string;
  name: string;
  slug: string;
  system_prompt_id: string;
  actions: AgentAction[];
  reactions: AgentReaction[];
};
export type Agency = {
  prompts: {
    qualify_lead: Prompt & {
      id: 'a1b2c3d4-e5f6-4321-8901-abcdef123456';
      name: 'Qualify Lead';
      content: string;
      version: '1.0.0';
      variables: [
        {
          name: 'company_info';
          type: 'string';
          required: true;
        },
        {
          name: 'contact_name';
          type: 'string';
          required: true;
        },
        {
          name: 'budget_range';
          type: 'string';
          required: true;
        },
      ];
      slug: 'qualify_lead';
    };
    detect_super_qualified_lead: Prompt & {
      id: 'b2c3d4e5-f6a7-5432-9012-bcdef234567';
      name: 'Detect Super Qualified Lead';
      content: string;
      version: '1.0.0';
      variables: [
        {
          name: 'lead_details';
          type: 'string';
          required: true;
        },
        {
          name: 'budget_status';
          type: 'string';
          required: true;
        },
        {
          name: 'technical_requirements';
          type: 'string';
          required: true;
        },
      ];
      slug: 'detect_super_qualified_lead';
    };
    lead_urgency_assessment: Prompt & {
      id: 'c3d4e5f6-g7h8-6543-0123-cdefg345678';
      name: 'Lead Urgency Assessment';
      content: string;
      version: '1.0.0';
      variables: [
        {
          name: 'current_situation';
          type: 'string';
          required: true;
        },
        {
          name: 'timeline';
          type: 'string';
          required: true;
        },
        {
          name: 'competition_info';
          type: 'string';
          required: true;
        },
      ];
      slug: 'lead_urgency_assessment';
    };
    budget_alignment_verification: Prompt & {
      id: 'd4e5f6g7-h8i9-7654-2345-defgh456789';
      name: 'Budget Alignment Verification';
      content: string;
      version: '1.0.0';
      variables: [
        {
          name: 'budget_details';
          type: 'string';
          required: true;
        },
        {
          name: 'current_spend';
          type: 'string';
          required: true;
        },
        {
          name: 'decision_timeline';
          type: 'string';
          required: true;
        },
      ];
      slug: 'budget_alignment_verification';
    };
    technical_fit_assessment: Prompt & {
      id: 'e5f6g7h8-i9j0-8765-3456-efghi567890';
      name: 'Technical Fit Assessment';
      content: string;
      version: '1.0.0';
      variables: [
        {
          name: 'tech_stack';
          type: 'string';
          required: true;
        },
        {
          name: 'integration_needs';
          type: 'string';
          required: true;
        },
        {
          name: 'technical_constraints';
          type: 'string';
          required: true;
        },
      ];
      slug: 'technical_fit_assessment';
    };
    default_system_prompt: Prompt & {
      id: 'b2c3d4e5-f6g7-5432-9012-bcdef234567';
      name: 'Default system prompt';
      content: string;
      version: '1.0.0';
      variables: [];
      slug: 'default_system_prompt';
    };
  };
  agents: {
    lead_agent: Agent & {
      id: 'f6g7h8i9-j0k1-9876-4567-fghij678901';
      name: 'Lead Agent';
      slug: 'lead_agent';
      system_prompt_id: 'b2c3d4e5-f6g7-5432-9012-bcdef234567';
      actions: [
        {
          id: 'c8d9e0f1-g2h3-7654-3210-ghijkl456789';
          name: 'Qualify Lead';
          slug: 'qualify_lead';
          prompt_id: 'a1b2c3d4-e5f6-4321-8901-abcdef123456';
        },
      ];
      reactions: [
        {
          id: 'd4e5f6g7-h8i9-8765-4321-ijklmn890123';
          name: 'Detect Super Qualified Lead';
          slug: 'detect_super_qualified_lead';
          prompt_id: 'b2c3d4e5-f6a7-5432-9012-bcdef234567';
          triggers: [{ type: 'AFTER_ASSISTANT_MESSAGE' }];
        },
      ];
    };
  };
};
