create table {table_name} (
    id bigint generated by default as identity not null primary key,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create trigger trigger_updated_at_{table_name}
before update on {table_name}
for each row
execute function set_updated_at();

alter table {table_name} enable row level security;