create extension if not exists timescaledb;

-- LLM Logs (TimescaleDB Table)
create table llm_logs (
    id bigint generated by default as identity not null,
    uuid uuid not null default uuid_generate_v4(),
    project_id bigint references projects(id) not null,
    prompt_version_id bigint references prompt_versions(id) not null,
    prompt_variables jsonb not null,
    raw_input jsonb not null,
    raw_output jsonb,
    start_time timestamptz not null,
    end_time timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(id, created_at),
    unique(uuid, created_at)
);

create index on llm_logs(project_id, created_at);
create index on llm_logs(prompt_version_id, created_at);
create index on llm_logs(start_time, created_at);
create index on llm_logs(end_time, created_at);

create trigger trigger_updated_at_llm_logs
    before update on llm_logs
    for each row
    execute function set_updated_at();

select create_hypertable('llm_logs', 'created_at');